### ISSUE TITLE
A product tábla nem rendelkezik kép tárolására alkalmas mezővel

### ISSUE THREAD

**Issue by agvxov** [gyorkistamas/afp1_mini_newcodeorderby#1]
A '"review site"/product' recordjai nem képesek két tárolásra. Kérdés, hogy blob formában vagy elérési utként szeretnénk ezt tárolni.

**Comment by gyorkistamas** [comment]
A rövid időre való tekintettel, és hogy ez még a kis projekt, nem terveztünk képet tárolni a termékekről.
